/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.leijendary.spring.iamtemplate.event.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AccountSchema extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4221166365755645315L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AccountSchema\",\"namespace\":\"com.leijendary.spring.iamtemplate.event.schema\",\"fields\":[{\"name\":\"id\",\"type\":\"long\"},{\"name\":\"type\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"createdDate\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"createdBy\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AccountSchema> ENCODER =
      new BinaryMessageEncoder<AccountSchema>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AccountSchema> DECODER =
      new BinaryMessageDecoder<AccountSchema>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AccountSchema> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AccountSchema> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AccountSchema> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<AccountSchema>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AccountSchema to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AccountSchema from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AccountSchema instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AccountSchema fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long id;
   private java.lang.String type;
   private java.lang.String createdDate;
   private java.lang.String createdBy;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AccountSchema() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param type The new value for type
   * @param createdDate The new value for createdDate
   * @param createdBy The new value for createdBy
   */
  public AccountSchema(java.lang.Long id, java.lang.String type, java.lang.String createdDate, java.lang.String createdBy) {
    this.id = id;
    this.type = type;
    this.createdDate = createdDate;
    this.createdBy = createdBy;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return type;
    case 2: return createdDate;
    case 3: return createdBy;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: type = value$ != null ? value$.toString() : null; break;
    case 2: createdDate = value$ != null ? value$.toString() : null; break;
    case 3: createdBy = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'type' field.
   * @return The value of the 'type' field.
   */
  public java.lang.String getType() {
    return type;
  }


  /**
   * Sets the value of the 'type' field.
   * @param value the value to set.
   */
  public void setType(java.lang.String value) {
    this.type = value;
  }

  /**
   * Gets the value of the 'createdDate' field.
   * @return The value of the 'createdDate' field.
   */
  public java.lang.String getCreatedDate() {
    return createdDate;
  }


  /**
   * Sets the value of the 'createdDate' field.
   * @param value the value to set.
   */
  public void setCreatedDate(java.lang.String value) {
    this.createdDate = value;
  }

  /**
   * Gets the value of the 'createdBy' field.
   * @return The value of the 'createdBy' field.
   */
  public java.lang.String getCreatedBy() {
    return createdBy;
  }


  /**
   * Sets the value of the 'createdBy' field.
   * @param value the value to set.
   */
  public void setCreatedBy(java.lang.String value) {
    this.createdBy = value;
  }

  /**
   * Creates a new AccountSchema RecordBuilder.
   * @return A new AccountSchema RecordBuilder
   */
  public static com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder newBuilder() {
    return new com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder();
  }

  /**
   * Creates a new AccountSchema RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AccountSchema RecordBuilder
   */
  public static com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder newBuilder(com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder other) {
    if (other == null) {
      return new com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder();
    } else {
      return new com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder(other);
    }
  }

  /**
   * Creates a new AccountSchema RecordBuilder by copying an existing AccountSchema instance.
   * @param other The existing instance to copy.
   * @return A new AccountSchema RecordBuilder
   */
  public static com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder newBuilder(com.leijendary.spring.iamtemplate.event.schema.AccountSchema other) {
    if (other == null) {
      return new com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder();
    } else {
      return new com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder(other);
    }
  }

  /**
   * RecordBuilder for AccountSchema instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AccountSchema>
    implements org.apache.avro.data.RecordBuilder<AccountSchema> {

    private long id;
    private java.lang.String type;
    private java.lang.String createdDate;
    private java.lang.String createdBy;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.createdDate)) {
        this.createdDate = data().deepCopy(fields()[2].schema(), other.createdDate);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.createdBy)) {
        this.createdBy = data().deepCopy(fields()[3].schema(), other.createdBy);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing AccountSchema instance
     * @param other The existing instance to copy.
     */
    private Builder(com.leijendary.spring.iamtemplate.event.schema.AccountSchema other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.type)) {
        this.type = data().deepCopy(fields()[1].schema(), other.type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.createdDate)) {
        this.createdDate = data().deepCopy(fields()[2].schema(), other.createdDate);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.createdBy)) {
        this.createdBy = data().deepCopy(fields()[3].schema(), other.createdBy);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder setId(long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder clearId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'type' field.
      * @return The value.
      */
    public java.lang.String getType() {
      return type;
    }


    /**
      * Sets the value of the 'type' field.
      * @param value The value of 'type'.
      * @return This builder.
      */
    public com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder setType(java.lang.String value) {
      validate(fields()[1], value);
      this.type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'type' field has been set.
      * @return True if the 'type' field has been set, false otherwise.
      */
    public boolean hasType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'type' field.
      * @return This builder.
      */
    public com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder clearType() {
      type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdDate' field.
      * @return The value.
      */
    public java.lang.String getCreatedDate() {
      return createdDate;
    }


    /**
      * Sets the value of the 'createdDate' field.
      * @param value The value of 'createdDate'.
      * @return This builder.
      */
    public com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder setCreatedDate(java.lang.String value) {
      validate(fields()[2], value);
      this.createdDate = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'createdDate' field has been set.
      * @return True if the 'createdDate' field has been set, false otherwise.
      */
    public boolean hasCreatedDate() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'createdDate' field.
      * @return This builder.
      */
    public com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder clearCreatedDate() {
      createdDate = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'createdBy' field.
      * @return The value.
      */
    public java.lang.String getCreatedBy() {
      return createdBy;
    }


    /**
      * Sets the value of the 'createdBy' field.
      * @param value The value of 'createdBy'.
      * @return This builder.
      */
    public com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder setCreatedBy(java.lang.String value) {
      validate(fields()[3], value);
      this.createdBy = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'createdBy' field has been set.
      * @return True if the 'createdBy' field has been set, false otherwise.
      */
    public boolean hasCreatedBy() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'createdBy' field.
      * @return This builder.
      */
    public com.leijendary.spring.iamtemplate.event.schema.AccountSchema.Builder clearCreatedBy() {
      createdBy = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AccountSchema build() {
      try {
        AccountSchema record = new AccountSchema();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.type = fieldSetFlags()[1] ? this.type : (java.lang.String) defaultValue(fields()[1]);
        record.createdDate = fieldSetFlags()[2] ? this.createdDate : (java.lang.String) defaultValue(fields()[2]);
        record.createdBy = fieldSetFlags()[3] ? this.createdBy : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AccountSchema>
    WRITER$ = (org.apache.avro.io.DatumWriter<AccountSchema>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AccountSchema>
    READER$ = (org.apache.avro.io.DatumReader<AccountSchema>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.id);

    out.writeString(this.type);

    out.writeString(this.createdDate);

    out.writeString(this.createdBy);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.id = in.readLong();

      this.type = in.readString();

      this.createdDate = in.readString();

      this.createdBy = in.readString();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.id = in.readLong();
          break;

        case 1:
          this.type = in.readString();
          break;

        case 2:
          this.createdDate = in.readString();
          break;

        case 3:
          this.createdBy = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










