auth:
  issuer: https://dev.leijendary.com

verification:
  password:
    nominate:
      url: https://dev.leijendary.com/password/nominate

spring:
  cloud:
    aws:
      cloudFront:
        url: https://cdn.dev.leijendary.com
      s3:
        bucketName: leijendary-api-dev
