auth:
  issuer: http://localhost

verification:
  password:
    nominate:
      url: http://localhost:3000/password/nominate

spring:
  datasource:
    primary:
      maximumPoolSize: 5
    readonly:
      maximumPoolSize: 5
  data:
    redis:
      ssl: false
  kafka:
    jaas:
      enabled: false
    properties:
      sasl.mechanism: PLAIN
    security:
      protocol: PLAINTEXT