info:
  app:
    organization: leijendary
    group: ${group}
    name: ${name}
    description: ${description}
    version: ${version}
  api:
    termsOfService:
    contact:
      name: Jonathan Leijendekker
      url: https://leijendary.com
      email:
    license:
      name: Jonathan Leijendekker
      url: https://leijendary.com
    servers:
      - url: http://localhost
        description: Local
      - url: https://api.dev.leijendary.com
        description: Development
      - url: https://api.test.leijendary.com
        description: Testing
      - url: https://api.staging.leijendary.com
        description: Staging
      - url: https://api.leijendary.com
        description: Production

auth:
  issuer: https://leijendary.com
  keyId: spring-iam-template
  accessToken:
    expiry: 7d
    privateKey:
    publicKey:
  refreshToken:
    expiry: 200d
    privateKey:
    publicKey:
  social:
    apple:
      clientId:
      issuer: https://appleid.apple.com
      jwkSetUri: https://appleid.apple.com/auth/keys
    facebook:
      url: https://graph.facebook.com/v16.0
      profilePath: /me?fields=id,first_name,last_name,email,picture
    google:
      clientId:
      issuer: https://accounts.google.com
      jwkSetUri: https://www.googleapis.com/oauth2/v3/certs
  system:
    principal: System

encrypt:
  key:
  salt:

verification:
  expiry: 2h
  timeout: 60s
  register:
    templateId: register-verify
  password:
    nominate:
      templateId: password-nominate
      url:
    reset:
      templateId: password-reset
  email:
    templateId: email-change

spring:
  application:
    name: \${info.app.name}
  cache:
    type: REDIS
    redis:
      timeToLive: 5h
  cloud:
    aws:
      cloudFront:
        url:
        publicKeyId:
        privateKey:
        signatureDuration: 30m
      s3:
        bucketName:
        signatureDuration: 30m
  datasource:
    primary:
      poolName: Primary
      jdbcUrl:
      username:
      password:
      dataSourceProperties:
        cachePrepStmts: true
        rewriteBatchedStatements: true
        useServerPrepStmts: true
    readonly:
      poolName: Read-only
      jdbcUrl:
      username:
      password:
  data:
    jdbc:
      repositories:
        enabled: false
    redis:
      repositories:
        enabled: false
      host:
      port:
      ssl:
        enabled: true
      username:
      password:
    web:
      pageable:
        maxPageSize: 100
  jackson:
    defaultPropertyInclusion: NON_ABSENT
  jpa:
    openInView: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        jdbc:
          batch_size: 1000
      jakarta:
        persistence:
          lock:
            timeout: 2000
          sharedCache:
            mode: UNSPECIFIED
  kafka:
    bootstrapServers:
    clientId: \${info.app.name}
    consumer:
      groupId: \${info.app.name}
      properties:
        partition:
          assignment:
            strategy: org.apache.kafka.clients.consumer.CooperativeStickyAssignor
    jaas:
      enabled: true
      loginModule: org.apache.kafka.common.security.scram.ScramLoginModule
      options:
        username:
        password:
    producer:
      acks: all
    properties:
      interceptor:
        classes: com.leijendary.spring.template.iam.core.interceptor.KafkaInterceptor
      sasl:
        mechanism: SCRAM-SHA-256
    security:
      protocol: SASL_SSL
    topic:
      notificationEmail:
        name: \${info.app.organization}.notification.email
      notificationPush:
        name: \${info.app.organization}.notification.push
      notificationSms:
        name: \${info.app.organization}.notification.sms
  main:
    bannerMode: LOG
  messages:
    basename: messages.access, messages.error, messages.notification, messages.validation
  mvc:
    throwExceptionIfNoHandlerFound: true
  sendgrid:
    apiKey:
  web:
    resources:
      addMappings: false

server:
  error:
    whitelabel:
      enabled: false
  http2:
    enabled: true
  port: 80

springdoc:
  pathsToMatch: /api/**
  swaggerUi:
    disableSwaggerDefaultUrl: true

management:
  endpoint:
    health:
      showDetails: ALWAYS
  endpoints:
    web:
      exposure:
        include: '*'
  otlp:
    metrics:
      export:
        url:
    tracing:
      endpoint:

logging:
  level:
    liquibase:
      hub: ERROR
    org:
      apache:
        kafka: ERROR
  pattern:
    level: '%5p [\${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
