auth:
  issuer: https://leijendary.com

verification:
  password:
    nominate:
      url: https://leijendary.com/password/nominate

spring:
  cloud:
    aws:
      cloudFront:
        distributionId:
        url: https://cdn.leijendary.com
      s3:
        bucketName: leijendary-api-prod
  kafka:
    listener:
      concurrency: 40
    topic:
      notificationEmail:
        partitions: 20
      notificationPush:
        partitions: 10
      notificationSms:
        partitions: 10

springdoc:
  apiDocs:
    enabled: false
  swaggerUi:
    enabled: false
