auth:
  issuer: http://localhost

verification:
  password:
    nominate:
      url: http://localhost:3000/password/nominate

spring:
  cloud:
    aws:
      cloudFront:
        distributionId:
        url: https://cdn.dev.leijendary.com
      s3:
        bucketName: leijendary-api-dev
  data:
    redis:
      ssl:
        enabled: false
  datasource:
    primary:
      maximumPoolSize: 5
    readonly:
      maximumPoolSize: 5
  kafka:
    jaas:
      enabled: false
    properties:
      sasl:
        mechanism: PLAIN
    security:
      protocol: PLAINTEXT

management:
  tracing:
    probability: 1.0
