verification:
  password:
    nominate:
      url: https://staging.leijendary.com/password/nominate

spring:
  cloud:
    aws:
      cloudFront:
        url: https://cdn.staging.leijendary.com
      s3:
        bucketName: leijendary-api-staging
