apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-iam-template-config
  namespace: template
data:
  SPRING_PROFILES_ACTIVE: dev
  SPRING_DATASOURCE_PRIMARY_JDBC_URL: "jdbc:postgresql://postgres-service.database.svc.cluster.local:5432/spring_iam_template"
  SPRING_DATASOURCE_PRIMARY_USERNAME: postgres
  SPRING_DATASOURCE_READONLY_JDBC_URL: "jdbc:postgresql://postgres-service.database.svc.cluster.local:5432/spring_iam_template"
  SPRING_DATASOURCE_READONLY_USERNAME: postgres
  SPRING_CLOUD_AWS_CREDENTIALS_INSTANCE_PROFILE: "false"
  SPRING_CLOUD_AWS_REGION_INSTANCE_PROFILE: "false"
  SPRING_CLOUD_AWS_REGION_STATIC: eu-central-1
  SPRING_CLOUD_AWS_SNS_PLATFORM_APPLE_ARN:
  SPRING_CLOUD_AWS_SNS_PLATFORM_FIREBASE_ARN:
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-service.kafka.svc.cluster.local:9092
  SPRING_DATA_REDIS_HOST: redis-service.cache.svc.cluster.local
  SPRING_DATA_REDIS_PORT: "6379"
  AWS_EC2_METADATA_DISABLED: "true"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://jaeger-service.monitoring.svc.cluster.local:9411/api/v2/spans
  AUTH_ISSUER: http://localhost
  AUTH_ACCESS_TOKEN_PRIVATE_KEY:
  AUTH_ACCESS_TOKEN_PUBLIC_KEY:
  AUTH_REFRESH_TOKEN_PRIVATE_KEY:
  AUTH_REFRESH_TOKEN_PUBLIC_KEY:
  VERIFICATION_EMAIL_URL: http://localhost:3000/email/verify/{code}
  VERIFICATION_REGISTER_URL: http://localhost:3000/register/verify/{code}
  VERIFICATION_PASSWORD_CHANGE_URL: http://localhost:3000/password/change/{code}
  VERIFICATION_PASSWORD_RESET_URL: http://localhost:3000/password/reset/{code}
