apiVersion: v1
kind: Secret
metadata:
  name: spring-iam-template-secret
  namespace: template
type: Opaque
data:
  # 12345678
  SPRING_DATASOURCE_PRIMARY_PASSWORD: MTIzNDU2Nzg=
  # 12345678
  SPRING_DATASOURCE_READONLY_PASSWORD: MTIzNDU2Nzg=
  SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY:
  SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY:
  ENCRYPT_KEY: RUZGYlVmVjRCQjI1MEd6bm1IZGlRMWVZcjc5cTh6U3NrUEFtelZQZQ==
  ENCRYPT_SALT: MDhkYmYxNzVjYmViOTFmMw==
